add user

diff --git a/auto/users b/auto/users
--- a/auto/users
+++ b/auto/users
@@ -1,11 +1,20 @@
-
+#!/bin/sh
 # Copyright (C) zhao
 
+if [ $UID -ne 0  ]; then
+    echo "root user are required to run this script" 
+    exit 1;
+fi
+
+passwd="Nbppassw0rd"
 SFTP=sftp
 WWW=www
 NBPVG=nbpvg
+NBPVG_PASSWD=${NBPVG_PASSWD:-$passwd}
 NBPDOWN=nbpdown
+NBPDOWN_PASSWD=${NBPDOWN_PASSWD:-$passwd}
 NBPWWW=nbpwww
+NBPWWW_PASSWD=${NBPWWW_PASSWD:-$passwd}
 SFTP_HOME=/home/sftp/NBP_AAS
 NBPVG_HOME=$SFTP_HOME"/vg_upload"
 
@@ -37,18 +46,37 @@ fi
 grep "$NBPVG" /etc/passwd >& /dev/null
 if [ $? != 0 ]; then
 	echo -e "add user: "$NBPVG
-	useradd -d $SFTP_HOME -g $SFTP -M -s /sbin/nologin
+	useradd -d $SFTP_HOME -g $SFTP -M -s /sbin/nologin -p $NBPVG_PASSWD $NBPVG
 fi
 
 grep "$NBPDOWN" /etc/passwd >& /dev/null
 if [ $? != 0 ]; then
 	echo -e "add user: "$NBPDOWN
-	useradd -d $SFTP_HOME -g $SFTP -G $WWW -M -s /sbin/nologin
+	useradd -d $SFTP_HOME -g $SFTP -G $WWW -M -s /sbin/nologin -p $NBPDOWN_PASSWD $NBPDOWN
 fi
 
 grep "$NBPWWW" /etc/passwd >& /dev/null
 if [ $? != 0 ]; then
 	echo -e "add user: "$NBPWWW
-	useradd -d $SFTP_HOME -g $WWW -M -s /sbin/nologin
+	useradd -d $SFTP_HOME -g $WWW -M -s /sbin/nologin -p $NBPWWW_PASSWD $NBPWWW
+fi
+
+#check user 
+grep "$NBPVG" /etc/passwd >& /dev/null
+if [ $? != 0 ]; then
+	echo -e $TEST_FAIL"user: "$NBPVG" create failed"
+	exit 1;
+fi
+
+grep "$NBPDOWN" /etc/passwd >& /dev/null
+if [ $? != 0 ]; then
+	echo -e $TEST_FAIL"user: "$NBPDOWN" create failed"
+	exit 1;
+fi
+
+grep "$NBPWWW" /etc/passwd >& /dev/null
+if [ $? != 0 ]; then
+	echo -e $TEST_FAIL"user: "$NBPWWW" create failed"
+	exit 1;
 fi
 
diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,10 +5,10 @@
 LC_ALL=C
 export LC_ALL
 
-#if [ $UID -ne 0 ]; then
-#	echo "root user are required to run this script"
-#	exit 1;
-#fi
+if [ $UID -ne 0 ]; then
+	echo "root user are required to run this script"
+	exit 1;
+fi
 
 CURR_DIR=`pwd`
 cd $CURR_DIR
@@ -36,13 +36,40 @@ if [ $? != 0 ]; then
 fi
 echo -e $TEST_OK"make nginx"
 
-#make install
+make install
 
 if [ $? != 0 ]; then
 	echo -e $TEST_FAIL"install nginx failed"
 	exit 1;
 fi
 echo -e $TEST_OK"install nginx"
+
+cp -f $NGINX_CONF_SRC $NGINX_CONF_PATH
+ 
+if [ $? != 0 ]; then
+	echo -e $TEST_FAIL"deploy $NGINX_CONF_SRC"
+	exit 1;
+fi
+echo -e $TEST_OK"deploy $NGINX_CONF_SRC"
+
+echo -e "Try to start nginx: $NGINX_SBIN_PATH"
+
+$NGINX_SBIN_PATH -t
+
+if [ $? != 0 ]; then
+	echo -e $TEST_FAIL"check nginx configuration: $NGINX_CONF_PATH"
+	exit 1;
+fi
+echo -e $TEST_OK"start nginx; $NGINX_CONF_PATH"
+
+$NGINX_SBIN_PATH
+
+if [ $? != 0 ]; then
+	echo -e $TEST_FAIL"start nginx: $NGINX_SBIN_PATH"
+	exit 1;
+fi
+echo -e $TEST_OK"start nginx; $NGINX_SBIN_PATH"
+
 
 crontask="01 00 * * * $CURR_DIR/src/logrotate"
 cat << END  > $CURR_DIR/src/rotate.cron
